version: "3"

services:
    db:
        container_name: postgres_service
        image: postgres:11
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=test_db

    web:
        container_name: web_service
        build:
            context: .
            dockerfile: DockerfileAPI
        command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8080 --reload"

        volumes:
            - ./fastAPI-deploy/:/code

        working_dir: /code/app
        ports:
            - "8080:8080"
        depends_on:
            - db

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "5050:5050"
        depends_on:
            - db
        depends_on:
            - triton

    
    triton:
        image: nvcr.io/nvidia/tritonserver:21.10-py3
        shm_size: 1g
        ulimits:
            memlock: -1
            stack: 67108864
        ports:
            - "8000:8000"
            - "8001:8001"
            - "8002:8002"
        volumes:
            - ./triton-deploy/models:/triton/models
            - ./triton-deploy/plugins:/triton/plugins
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
        environment:
            - LD_PRELOAD=/triton/plugins/yolov4/liblayerplugin.so

        working_dir: /triton

        command: ["tritonserver", "--model-repository=/triton/models", "--grpc-infer-allocation-pool-size=16"]
        
