version: "3"

services:
    db:
        container_name: postgres_service
        image: postgres:11
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=test_db

    web:
        container_name: web_service
        build:
            context: .
            dockerfile: DockerfileAPI
        command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8080 --reload"

        volumes:
            - ./fastAPI-deploy/:/code

        working_dir: /code/app
        ports:
            - "8080:8080"
        depends_on:
            - db

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "5050:5050"
        depends_on:
            - db