"""empty message

Revision ID: d143974b45a5
Revises: dfdc2e721479
Create Date: 2022-12-13 15:45:11.382034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd143974b45a5'
down_revision = 'dfdc2e721479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
