"""First migration

Revision ID: df57f27cec24
Revises: 
Create Date: 2022-12-07 17:54:28.426978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df57f27cec24"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("videos")
    # ### end Alembic commands ###
