"""empty message

Revision ID: dfdc2e721479
Revises: df57f27cec24
Create Date: 2022-12-13 15:42:13.106458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdc2e721479'
down_revision = 'df57f27cec24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
